server {
    listen 80;
    root /usr/share/nginx/html;

    location /glyph {
        try_files $uri $uri/ $uri.html /glyph/index.html;
    }

    # Health check endpoint for Docker
    location /health {
        return 200 "ok";
        add_header Content-Type text/plain;
    }
}
